In [145]:
import tensorflow as tf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras import layers
import tensorflow.keras
import warnings
warnings.filterwarnings("ignore")
from sklearn import metrics
import math
from math import log
import numpy as np 
import matplotlib 
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras import layers
import tensorflow.keras
import warnings
warnings.filterwarnings("ignore")
%matplotlib inline


In [ ]:
#The following part is to load in the data in the first time. Data coming from 5 diferent kinds of websites, 
#labeled below each chunk. Each row would be renamed as T + number.
#The columns are all the nouns included in all the articles.

In [76]:
# let Nouns on the column names:
test11 = pd.read_csv('test11.csv', header = 0, names = None).transpose() 
test11.rename(columns = test11.iloc[0], inplace = True)
test11.drop(test11.index[0], inplace=True)

# Change the row title to no. of texts
test11.rename({"WC" : 'T11'}, axis='index', inplace = True)
#欧乐影院

In [77]:
test13 = pd.read_csv('test13.csv', header = 0, names = None).transpose()
test13.rename(columns = test13.iloc[0], inplace = True)
test13.drop(test13.index[0], inplace=True)
test13.rename({"WC" : 'T13'}, axis='index', inplace = True)
#UR official website (REU)

In [78]:
test12 = pd.read_csv('test12.csv', header = 0, names = None).transpose()
test12.rename(columns = test12.iloc[0], inplace = True)
test12.drop(test12.index[0], inplace=True)
test12.rename({"WC" : 'T12'}, axis='index', inplace = True)
#New York Time

In [79]:
test14 = pd.read_csv('test14.csv', header = 0, names = None).transpose()
test14.rename(columns = test14.iloc[0], inplace = True)
test14.drop(test14.index[0], inplace=True)
test14.rename({"WC" : 'T14'}, axis='index', inplace = True)
#League of Legends

In [80]:
test15 = pd.read_csv('test15.csv', header = 0, names = None).transpose()
test15.rename(columns = test15.iloc[0], inplace = True)
test15.drop(test15.index[0], inplace=True)
test15.rename({"WC" : 'T15'}, axis='index', inplace = True)
#NBA

In [81]:
test16 = pd.read_csv('test16.csv', header = 0, names = None).transpose()
test16.rename(columns = test16.iloc[0], inplace = True)
test16.drop(test16.index[0], inplace=True)
test16.rename({"WC" : 'T16'}, axis='index', inplace = True)
#欧乐影院

In [82]:
test17 = pd.read_csv('test17.csv', header = 0, names = None).transpose()
test17.rename(columns = test17.iloc[0], inplace = True)
test17.drop(test17.index[0], inplace=True)
test17.rename({"WC" : 'T17'}, axis='index', inplace = True)
#UR

In [83]:
test18 = pd.read_csv('test18.csv', header = 0, names = None).transpose()
test18.rename(columns = test18.iloc[0], inplace = True)
test18.drop(test18.index[0], inplace=True)
test18.rename({"WC" : 'T18'}, axis='index', inplace = True)
#NYT

In [84]:
test19 = pd.read_csv('test19.csv', header = 0, names = None).transpose()
test19.rename(columns = test19.iloc[0], inplace = True)
test19.drop(test19.index[0], inplace=True)
test19.rename({"WC" : 'T19'}, axis='index', inplace = True)
#LOL

In [85]:
test20 = pd.read_csv('test20.csv', header = 0, names = None).transpose()
test20.rename(columns = test20.iloc[0], inplace = True)
test20.drop(test20.index[0], inplace=True)
test20.rename({"WC" : 'T20'}, axis='index', inplace = True)
#LOL

In [86]:
test111 = pd.read_csv('test111.csv', header = 0, names = None).transpose()
test111.rename(columns = test111.iloc[0], inplace = True)
test111.drop(test111.index[0], inplace=True)
test111.rename({"WC" : 'T111'}, axis='index', inplace = True)
#欧乐

In [87]:
test112 = pd.read_csv('test112.csv', header = 0, names = None).transpose()
test112.rename(columns = test112.iloc[0], inplace = True)
test112.drop(test112.index[0], inplace=True)
test112.rename({"WC" : 'T112'}, axis='index', inplace = True)
#欧乐

In [88]:
test113 = pd.read_csv('test113.csv', header = 0, names = None).transpose()
test113.rename(columns = test113.iloc[0], inplace = True)
test113.drop(test113.index[0], inplace=True)
test113.rename({"WC" : 'T113'}, axis='index', inplace = True)
#LOL

In [89]:
test114 = pd.read_csv('test114.csv', header = 0, names = None).transpose()
test114.rename(columns = test114.iloc[0], inplace = True)
test114.drop(test114.index[0], inplace=True)
test114.rename({"WC" : 'T114'}, axis='index', inplace = True)
#UR

In [ ]:
#This is to combine the data to form a big dataset inorder to use. Labels would be added as column "output"
#at the back of the dataset.

In [121]:
data = [test11, test12, test13, test14, test15, test16, test17, test18, test19, test20, test111, test112, test113, test114]
data = pd.concat(data)
data.fillna(0, inplace = True)
data["output"] = [1, 2, 3, 4, 5, 1, 3, 2, 4, 5, 1, 1, 5, 3]
data

日本  美国  var  动漫  鬼头明里  下野纮  松冈祯丞  小西克幸  吴磊  大陆  ...  hilda  \
T11   30  15   13  13    12   12    12    12  12  12  ...      0   
T12    0   0    0   0     0    0     0     0   0   0  ...      0   
T13    0   0    0   0     0    0     0     0   0   0  ...      0   
T14    0   0    0   0     0    0     0     0   0   0  ...      0   
T15    0   0    4   0     0    0     0     0   0   0  ...      0   
T16   25   5    0   4    15   15    15    15   5  10  ...      0   
T17    0   0    0   0     0    0     0     0   0   0  ...      0   
T18    0   0    0   0     0    0     0     0   0   0  ...      0   
T19    0   0    0   0     0    0     0     0   0   0  ...      0   
T20    0   0    7   0     0    0     0     0   0   0  ...      0   
T111  25   5    0   4    15   15    15    15   5   0  ...      0   
T112  25   5    0   4    15   15    15    15   5   0  ...      0   
T113   0   0    0   0     0    0     0     0   0   0  ...      0   
T114   0   0    0   0     0    0     0     0   0   0  ...      5   

      rochestergivinglinks  alumnioptics  optics.centershopkins  opticscenter  \
T11                      0             0                      0             0   
T12                      0             0                      0             0   
T13                      0             0                      0             0   
T14                      0             0                      0             0   
T15                      0             0                      0             0   
T16                      0             0                      0             0   
T17                      0             0                      0             0   
T18                      0             0                      0             0   
T19                      0             0                      0             0   
T20                      0             0                      0             0   
T111                     0             0                      0             0   
T112                     0             0                      0             0   
T113                     0             0                      0             0   
T114                     5             5                      4             4   

      programsince  students.optics  hajim  intranetphone/email  output  
T11              0                0      0                    0       1  
T12              0                0      0                    0       2  
T13              0                0      0                    0       3  
T14              0                0      0                    0       4  
T15              0                0      0                    0       5  
T16              0                0      0                    0       1  
T17              0                0      0                    0       3  
T18              0                0      0                    0       2  
T19              0                0      0                    0       4  
T20              0                0      0                    0       5  
T111             0                0      0                    0       1  
T112             0                0      0                    0       1  
T113             0                0      0                    0       5  
T114             4                4      2                    1       3  

[14 rows x 2445 columns]

In [ ]:
#This is to import some new dataset. There are two kinds of websites.
#One is UR Physics department, and one is UR History department.

In [170]:
test0 = pd.read_csv('test0.csv', header = 0, names = None).transpose()
test0.rename(columns = test0.iloc[0], inplace = True)
test0.drop(test0.index[0], inplace=True)
test0.rename({"WC" : 'T0'}, axis='index', inplace = True)
#Phy

In [171]:
test1 = pd.read_csv('test1.csv', header = 0, names = None).transpose()
test1.rename(columns = test1.iloc[0], inplace = True)
test1.drop(test1.index[0], inplace=True)
test1.rename({"WC" : 'T1'}, axis='index', inplace = True)
#Phy

In [172]:
test2 = pd.read_csv('test2.csv', header = 0, names = None).transpose()
test2.rename(columns = test2.iloc[0], inplace = True)
test2.drop(test2.index[0], inplace=True)
test2.rename({"WC" : 'T2'}, axis='index', inplace = True)
#Phy

In [173]:
test3 = pd.read_csv('test3.csv', header = 0, names = None).transpose()
test3.rename(columns = test3.iloc[0], inplace = True)
test3.drop(test3.index[0], inplace=True)
test3.rename({"WC" : 'T3'}, axis='index', inplace = True)
#Phy

In [174]:
test4 = pd.read_csv('test4.csv', header = 0, names = None).transpose()
test4.rename(columns = test4.iloc[0], inplace = True)
test4.drop(test4.index[0], inplace=True)
test4.rename({"WC" : 'T4'}, axis='index', inplace = True)
#Phy

In [175]:
test5 = pd.read_csv('test5.csv', header = 0, names = None).transpose()
test5.rename(columns = test5.iloc[0], inplace = True)
test5.drop(test5.index[0], inplace=True)
test5.rename({"WC" : 'T5'}, axis='index', inplace = True)
#Hist

In [176]:
test6 = pd.read_csv('test6.csv', header = 0, names = None).transpose()
test6.rename(columns = test6.iloc[0], inplace = True)
test6.drop(test6.index[0], inplace=True)
test6.rename({"WC" : 'T6'}, axis='index', inplace = True)
#Hist

In [177]:
test7 = pd.read_csv('test7.csv', header = 0, names = None).transpose()
test7.rename(columns = test7.iloc[0], inplace = True)
test7.drop(test7.index[0], inplace=True)
test7.rename({"WC" : 'T7'}, axis='index', inplace = True)
#Hist

In [178]:
test8 = pd.read_csv('test8.csv', header = 0, names = None).transpose()
test8.rename(columns = test8.iloc[0], inplace = True)
test8.drop(test8.index[0], inplace=True)
test8.rename({"WC" : 'T8'}, axis='index', inplace = True)
#Hist

In [179]:
test9 = pd.read_csv('test9.csv', header = 0, names = None).transpose()
test9.rename(columns = test9.iloc[0], inplace = True)
test9.drop(test9.index[0], inplace=True)
test9.rename({"WC" : 'T9'}, axis='index', inplace = True)
#Hist

In [188]:
data_new = [test0, test1, test2, test3, test4, test5, test6, test7, test8, test9]
data_new = pd.concat(data_new)
data_new.fillna(0, inplace = True)
data_new["output"] = [1, 1, 1, 1, 1, 2, 2, 2, 2, 2]
data_new

optics  physics  professor  university  rochester  press  semiconductor  \
T0      55       36         35          34         34     28             21   
T1       0       29          5          20         27      0              0   
T2       0       22          5          26         27      0              0   
T3      21       89         46          82         55      0              0   
T4       0       36         49          41         34      0              0   
T5       0        0          5          26         27      0              0   
T6       0        0         17          58         46     19              0   
T7       0        0          0          32         27      6              0   
T8       0        0          5          33         27      0              0   
T9       0        0          5          20         27      0              0   

    lasers  fiber  ed  ...  constantinople  historiography  trent  suny  \
T0      21     21  21  ...               0               0      0     0   
T1       0      0   0  ...               0               0      0     0   
T2       0      0   0  ...               0               0      0     0   
T3       7      0   0  ...               0               0      0     0   
T4       0      0   0  ...               0               0      0     0   
T5       0      0   0  ...               0               0      0     0   
T6       0      0   0  ...               0               0      0     0   
T7       0      0   0  ...               0               0      0     0   
T8       0      0   6  ...               1               1      1     0   
T9       0      0   0  ...               0               0      0     6   

    brockport  ii  devoeadjunct  historyphd  facultyharry  output  
T0          0   0             0           0             0       1  
T1          0   0             0           0             0       1  
T2          0   0             0           0             0       1  
T3          0   0             0           0             0       1  
T4          0   0             0           0             0       1  
T5          0   0             0           0             0       2  
T6          0   0             0           0             0       2  
T7          0   0             0           0             0       2  
T8          0   0             0           0             0       2  
T9          6   6             5           5             1       2  

[10 rows x 746 columns]

In [ ]:
#This step is to cut the data set into training data and testing data. I picked 4 data as testing data.

In [91]:
#testing set
test_x = data.loc[['T111', 'T112', 'T113', 'T114']]
test_y = np.array(test_x['output'])
test_x = test_x.drop('output', axis = 1)
test_x = np.array(test_x)

#training set
train_x = data.drop(index = ['T111', 'T112', 'T113', 'T114'])
train_y = np.array(train_x['output'])
train_x = train_x.drop('output', axis = 1)
train_x = np.array(train_x)
train_y = np.array(train_y)

In [92]:
test_x

array([[25,  5,  0, ...,  0,  0,  0],
       [25,  5,  0, ...,  0,  0,  0],
       [ 0,  0,  0, ...,  0,  0,  0],
       [ 0,  0,  0, ...,  4,  2,  1]])

In [93]:
test_y

array([1, 1, 5, 3])

In [94]:
train_x

array([[30, 15, 13, ...,  0,  0,  0],
       [ 0,  0,  0, ...,  0,  0,  0],
       [ 0,  0,  0, ...,  0,  0,  0],
       ...,
       [ 0,  0,  0, ...,  0,  0,  0],
       [ 0,  0,  0, ...,  0,  0,  0],
       [ 0,  0,  7, ...,  0,  0,  0]])

In [95]:
train_y

array([1, 2, 3, 4, 5, 1, 3, 2, 4, 5])

In [191]:
data_new.loc['T3']

optics          21
physics         89
professor       46
university      82
rochester       55
                ..
ii               0
devoeadjunct     0
historyphd       0
facultyharry     0
output           1
Name: T3, Length: 746, dtype: int64

In [ ]:
#This to seperate testing and training data for the new dataset.

In [194]:
#testing set_new
test_x_new = data_new.loc[['T3', 'T4', 'T8', 'T9']]
test_y_new = np.array(test_x_new['output'])
test_x_new = test_x_new.drop('output', axis = 1)
test_x_new = np.array(test_x_new)

#training set_new
train_x_new = data_new.drop(index = ['T3', 'T4', 'T8', 'T9'])
train_y_new = np.array(train_x_new['output'])
train_x_new = train_x_new.drop('output', axis = 1)
train_x_new = np.array(train_x_new)
train_y_new = np.array(train_y_new)

In [195]:
test_x_new

array([[21, 89, 46, ...,  0,  0,  0],
       [ 0, 36, 49, ...,  0,  0,  0],
       [ 0,  0,  5, ...,  0,  0,  0],
       [ 0,  0,  5, ...,  5,  5,  1]])

In [ ]:
#From this part, SVM starts. a linear model would be fitted, and it would be used to predict result of testing set.

In [146]:
#SVM
from sklearn import svm
from sklearn import datasets
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import LinearSVC
from sklearn.datasets import make_blobs
from sklearn.metrics import confusion_matrix
import matplotlib.pyplot as plt

In [97]:
lin = svm.SVC(kernel = 'linear', C = 100)
lin.fit(train_x, train_y)
predict = lin.predict(test_x)
predict

array([1, 1, 1, 1])

In [98]:
acc_num = sum(test_y == predict)
acc_num

2

In [ ]:
#This SVM model is used to predict the new testing data.

In [199]:
#SVM_new
lin_new = svm.SVC(kernel = 'linear', C = 100)
lin_new.fit(train_x_new, train_y_new)
predict_new = lin_new.predict(test_x_new)
predict_new

array([1, 1, 2, 2])

In [200]:
acc_num_new = sum(test_y_new == predict_new)
acc_num_new

4